Melancholy: 0.5
Regret: 2.0
Shadow: 0.5
Harmony: 2.0
Wonder: 0.5
Curiosity: 2.0
Freedom: 2.0
'7': 2.0
'3': 2.0
Knowledge: 0.5
Existence: 0.5
Infinite Horizons: 0.5
Boundless Skies: 0.5
Stratagem: 0.5
Hope: 0.5
Obsession: 0.5
Legacy: 2.0
Responsibility: 0.5
Quest: 2.0
Fear: 2.0
Transformation: 2.0
Hidden Truth: 2.0
